#!/usr/bin/env ruby

require 'pp'
require 'config/environment'
require 'acts_as_edgy'

DirectedEdge::Edgy.database = DirectedEdge::Database.new('testdb', 'test')

AUTOBUILD = false

class User
  acts_as_edgy(:purchase, Order, LineItem, Variant, Product)
end

#class User
#  acts_as_edgy(:purchase,
#               DirectedEdge::Bridge.new(Order, :user_id, :id),
#               DirectedEdge::Bridge.new(LineItem, :order_id, :variant_id),
#               DirectedEdge::Bridge.new(Variant, :id, :product_id),
#               Product)
#end

def test_export
  DirectedEdge::Edgy.export
end

def test_related_products
  puts "Related Products:"
  product_id = 1035865702
  Product.find(product_id).edgy_related.each do |r|
    puts r.name
  end
  puts
end

def test_recommended_products
  puts "Recommended Products:"
  user_id = 1063649785
  User.find(user_id).edgy_recommended.each do |r|
    puts r.name
  end
  puts
end

test_export
test_related_products
test_recommended_products
